name: Playwright CI with Telegram Reporting

on:
  schedule:
    - cron: '0 23 * * *'  # Eksekusi setiap hari jam 06 WIB (23:00 UTC)
  workflow_dispatch:  # Memungkinkan eksekusi manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install
          pip install requests
          pip install requests playwright python-dotenv

      - name: Print working directory
        run: pwd

      - name: List directory contents
        run: ls -la

      - name: Verify file existence
        run: ls -la telegramReports/

      - name: Login with Password
        run: python telegramReports/login_password.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Login only input phone number
        run: python telegramReports/login_only_input_phoneNumber.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Login only input password
        run: python telegramReports/login_only_input_password.py
        env:
            TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
            CHAT_ID: ${{ secrets.CHAT_ID }}
            PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
            PASSWORD: ${{ secrets.PASSWORD }}
