name: Playwright CI with Telegram Reporting

on:
  schedule:
    - cron: '0 3 * * *'  # Eksekusi setiap hari jam 10 WIB (03:00 UTC)
  workflow_dispatch:  # Memungkinkan eksekusi manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install
          pip install requests  # Untuk kirim pesan ke Telegram

      - name: Run Playwright script
        run: python telegramReports\pwlogin_tele.py  # Ganti dengan nama file Python Anda
